services:
  gameserver:
    container_name: leagueserver
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEBIAN_FRONTEND=noninteractive
    ports:
      - "5119:5119/udp"
    volumes:
      - "./data/Settings:/core/src/GameServerConsole/bin/Release/net8.0/Settings"
    restart: unless-stopped